"""Curated evidence inventory; not an automated claim of exhaustive coverage."""
from pathlib import Path
import csv,json
rows=[
('S01','Official SOP','CSR&TI Berhampore','Technology Descriptor','Undated','https://csrtiber.res.in/Technologies_descriptor.pdf','Regional stage guidance','Full PDF reviewed','Not applicable','Local breed and Andhra Pradesh applicability unverified'),
('S02','Government project','NESAC and CMERTI','Muga Disease Early Warning System','2020 site copyright','https://apps.nesdr.gov.in/MDEWS/index.php','Environmental history and infestation','Official project page reviewed','Not acquired','Different species and outdoor setting; independent prospective validation unverified'),
('S03','Paper','Binson and Manju','Automated Disease Detection in Silkworms Using Machine Learning Techniques','2024','https://journal2.upgris.ac.id/index.php/asset/article/download/965/387','Larval image classification','Methods reviewed','Archive not located','Single-day controlled-background images; disease images from fifth day after infection'),
('S04','Dataset','Kajal Mungase and Shwetambari Chiwhane','Silkworm_Diseases_Dataset v1','2026-09-06','https://data.mendeley.com/datasets/g4b89vpp9c/1','Larval image categories','Publisher metadata reviewed','5529 images acquired and audited; 3843 representative groups; trained MobileNetV3 head','Overlap is a scene category; source-family independence unknown'),
('S05','Dataset','Silkworm Annotation','Silkworm Diseases v1','2024-11','https://universe.roboflow.com/silkworm-annotation-y6ztu/silkworm-diseases-y0bro/dataset/1','Larval detection','Publisher version page reviewed','Download interface not resolved','Augmented version images and object crops are not independent specimens'),
('S06','Repository','hokhoi02new','SilkLDP implementation','2025','https://github.com/hokhoi02new/silkworm_disease_segmentation_using_deeplearning_and_computer_vision_technology','Larval segmentation','Owner README reviewed','Sample only; full data described as proprietary','MIT code license does not grant rights to unavailable full data'),
('S07','Repository','yoctocandela','silkworm-fpga-ml','2026','https://github.com/yoctocandela/silkworm-fpga-ml','Classical crop classifier','Owner methods and data README reviewed','Images not redistributed','FPGA implementation absent; exporter split alone does not exclude leakage'),
('S08','Hackathon project','ZHAGARAM creators','Smart Sericulture System','2024-10','https://devpost.com/software/zhagaram-smart-sericulture-system','IoT and visual advisory application','Indexed creator page and gallery','Not acquired','Pilot and multilingual/predictive capabilities described as future work'),
('S09','Paper/project','Salamath et al.','Silk Shield','2025-05','https://iarjset.com/wp-content/uploads/2025/05/IARJSET.2025.125345.pdf','Image classification and climate suggestions','Full five-page PDF reviewed','No archive supplied','No auditable dataset count or numerical evaluation table'),
('S10','Paper','Shi et al.','WormSORT','2026-06-15','https://doi.org/10.1371/journal.pcbi.1014410','Individual video tracking','Primary full text reviewed','OSF retrieval failed','Two sequences at one institute; tracking is not disease lead-time validation'),
('S11','Dataset/paper','Nahiduzzaman et al.','Mulberry leaf dataset','2023','https://www.kaggle.com/datasets/nahiduzzaman13/mulberry-leaf-dataset/data','Leaf appearance classification','Publisher card and linked paper reviewed','1091 images acquired with original hashes','Single source; plant/session identity unknown; no larval labels'),
('S12','Dataset','Mendeley contributors','Mulberry cultivar dataset v3','Version 3','https://data.mendeley.com/datasets/ds45yy9jrc/3','Cultivar classification','Publisher metadata reviewed','Not acquired','Cultivar labels cannot become disease labels'),
('S13','Government data announcement','IndiaAI','Andhra Pradesh silkworm dataset announcement','Date unverified','https://www.linkedin.com/posts/indiaai_sericulture-opendata-aikosh-activity-7449837970519404544-cvI8','Advertised images/environment/outcomes','Official-account announcement','Official redirect resolved; AIKosh target currently unavailable; corpus not acquired','No verified sample size license or temporal linkage'),
('S14','Repository','Silkwormincubator','SilkWorm','Date unverified','https://github.com/Silkwormincubator/SilkWorm','Environmental sensor capture','Owner repository reviewed','No disease corpus established','Instrumentation comparator; not trained early-warning evidence'),
('S15','Paper lead','Publisher metadata','E-Nose-Based VOC Analysis for Rapid Detection of Grasserie Disease','2026','https://www.sciencedirect.com/science/article/pii/S2590123026033839','VOC sensors and ML','Indexed abstract; direct 403','Not acquired','Not RGB imagery; sampling and lead time unverified'),
('S16','Paper lead','Publisher metadata','Rapid BmNPV detection using FTIR spectroscopy and chemometric modelling','2026','https://www.sciencedirect.com/science/article/pii/S1386142526001708','Blood spectroscopy','Indexed abstract; direct 403','Not acquired','Requires a different sensing modality; performance not adopted'),
]
keys=['id','type','author_or_owner','title','date','url','task','evidence_access','data_access','critical_limitation']
root=Path(__file__).resolve().parent.parent
with (root/'docs/SOURCES.csv').open('w',newline='') as f:
 writer=csv.writer(f);writer.writerow(keys);writer.writerows(rows)
(root/'docs/SOURCES.json').write_text(json.dumps([dict(zip(keys,r)) for r in rows],indent=2)+'\n')
print(f'Wrote {len(rows)} curated sources')
