"""Create a standalone, printable evidence report from the repository's audited artifacts."""
import json,html
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path(__file__).resolve().parent.parent
escape=html.escape
larval=json.loads((ROOT/'artifacts/larval-model-report.json').read_text())
leaf=json.loads((ROOT/'artifacts/mulberry-model-report.json').read_text())
sources=json.loads((ROOT/'docs/SOURCES.json').read_text())
readiness=json.loads((ROOT/'artifacts/release-readiness.json').read_text())
score=larval['results'][larval['selected']]['test']
source_cards=''.join(f'<article><h3>{escape(s["id"])} · {escape(s["title"])}</h3><p>{escape(s["author_or_owner"])} · {escape(s["date"])} · {escape(s["type"])}</p><p><b>Task:</b> {escape(s["task"])}<br><b>Evidence:</b> {escape(s["evidence_access"])}<br><b>Data access:</b> {escape(s["data_access"])}</p><p><b>Limit:</b> {escape(s["critical_limitation"])}</p><a href="{escape(s["url"],quote=True)}">{escape(s["url"])}</a></article>' for s in sources)
limits=''.join(f'<li>{escape(x)}</li>' for x in larval['limitations'])
blockers=''.join(f'<tr><td>{escape(k)}</td><td>{escape(v)}</td></tr>' for k,v in readiness['externalEvidence'].items())
doc=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><title>SilkSense — implementation and evidence report</title><style>
@page{{size:A4;margin:18mm}}*{{box-sizing:border-box}}body{{font-family:system-ui,sans-serif;color:#243a31;max-width:1000px;margin:auto;padding:32px;line-height:1.65}}h1{{font-size:38px;line-height:1.2}}h2{{margin-top:36px;border-bottom:2px solid #cbdac8;padding-bottom:10px}}h3{{margin-bottom:6px}}p{{margin:8px 0}}.eyebrow{{letter-spacing:.15em;font-size:12px;color:#496a55}}.callout{{background:#eff5e9;padding:20px;border-left:4px solid #37694d}}.flow{{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0}}.flow span{{background:#183e35;color:white;border-radius:8px;padding:10px}}table{{width:100%;border-collapse:collapse;font-size:13px}}td,th{{border-bottom:1px solid #dce5d7;text-align:left;padding:10px;vertical-align:top}}article{{break-inside:avoid;border-bottom:1px solid #dce5d7;padding:14px 0}}a{{color:#24533f;overflow-wrap:anywhere;font-size:12px}}.muted{{color:#52614f}}@media print{{body{{padding:0}}.page{{break-before:page}}h2,h3{{break-after:avoid}}tr{{break-inside:avoid}}}}
</style></head><body><p class="eyebrow">SILKSENSE · ENGINEERING & RESEARCH RECORD</p><h1>From field observation<br>to traceable care.</h1><p class="muted">Release report · {datetime.now(timezone.utc).strftime('%d %B %Y')} UTC</p>
<div class="callout"><b>Implemented:</b> English/Telugu field workflows, mobile layouts, offline image inference, batch care and outcomes, account/farm authorization, and a tested recovery path.<br><b>Evidence boundary:</b> This is a working application with internal image-classification evidence. Disease diagnosis, prospective warning performance and yield benefit remain unvalidated.</div>
<h2>1. Product and reused foundation</h2><p>React, TypeScript and Vite provide the UI; i18next provides bundled English and Telugu copy. Dexie/IndexedDB stores device records and media. Express, SQLite and Express sessions provide the account API. Torchvision MobileNetV3-Small supplies ImageNet-pretrained convolutional features; a supervised classification head is trained on the audited larval image source. ONNX Runtime executes the same frozen graph on the server and in browser WebAssembly.</p>
<div class="flow"><span>Camera / upload</span><span>Image evidence</span><span>Batch assessment</span><span>Explainable care</span><span>Follow-up / review</span><span>Observed outcomes</span><span>Deferred sync</span></div>
<p>The product contribution is the connection between uncertain observations, image evidence, preventive care, follow-up and recorded outcomes. No new convolutional architecture is claimed. A low image score does not erase reported deaths or environmental concerns. Self-reported fresh feed is accompanied by a suspect-feed sensitivity scenario.</p>
<table><tr><th>Capability</th><th>Implemented behavior</th></tr><tr><td>Language and mobile</td><td>Telugu/English selection persists; forms retain drafts during switching; Telugu font and translations are bundled for offline use. Mobile navigation, forms, dialogs, tables and explanations adapt to narrow screens.</td></tr><tr><td>Capture and analysis</td><td>Camera, uploads and sampled video; quality checks and occlusion explanations. Explicit server/device inference selection with model checksum.</td></tr><tr><td>Records and care</td><td>Append-only assessments, interventions, reviews, follow-ups, observed onset and harvest outcomes. Missing measurements remain unknown.</td></tr><tr><td>Supervision</td><td>Farm, risk and latest-assessment date filters; visit priorities, descriptive trends and outcome comparisons.</td></tr><tr><td>Security</td><td>Hashed passwords, persisted sessions, login throttling, farm-scoped sync, supervisor-only review writes, linked-record checks and authenticated submission receipts. Separate local namespaces per account/assignment.</td></tr><tr><td>Deployment</td><td>Validated Caddy HTTPS configuration, account service template, verified SQLite backup and recovery commands. Public DNS and host activation pending.</td></tr></table>
<h2>2. Internal model evidence</h2><p>The larval source is <a href="https://data.mendeley.com/datasets/g4b89vpp9c/1">Mungase and Chiwhane, Silkworm_Diseases_Dataset v1 (CC BY 4.0)</a>. The acquisition contains {larval['acquired_images']:,} images. The audit retained {larval['representative_images']:,} source-family representatives and quarantined conflicting groups. Training, selection, calibration and test partitions are separate.</p>
<table><tr><th>Measure</th><th>Internal result</th><th>Interpretation</th></tr><tr><td>Test accuracy</td><td>{score['accuracy']*100:.2f}%</td><td>Single-source image holdout only</td></tr><tr><td>Macro F1</td><td>{score['macro_f1']:.4f}</td><td>Appearance classes, including Overlap</td></tr><tr><td>Network size</td><td>{larval['onnx_bytes']:,} bytes</td><td>Complete exported MobileNetV3 graph</td></tr></table>
<p>The backbone remains frozen; this is transfer learning of a classification head. Overlap is a scene condition, not a disease. The separate mulberry leaf classifier provides experimental feed-image review and cannot establish larval health. The overall low/medium/high priority score uses transparent engineering rules, not a trained predictor of future mortality.</p><ul>{limits}</ul>
<h2>3. Verification and evaluation pathway</h2><p>See the repository testing record for exact suite counts and commands. Browser tests exercise backend/device probability parity, camera permission handling, offline inference, capture/reload/sync, accessible screens, Telugu workflows and mobile widths. Account tests exercise anonymous rejection, cross-farm isolation, review permissions, logout, offline expiry and user workspace separation. Python evaluator tests check leakage rejection and parity with the frozen graph. These are software checks, not field-effectiveness studies.</p>
<p>The external evaluator consumes an independently supplied manifest with farm, batch, capture group, source, licence and label method. It rejects empty data and exact overlap with the acquisition corpus and reports confusion matrices, per-farm results, calibration error, score abstention and farm-cluster uncertainty. It does not tune the network or thresholds. Exact hashes cannot establish full acquisition independence; near-duplicate and annotation review remain necessary.</p>
<p>Prospective warning validation needs independently timed onset, a predeclared prediction horizon, negative follow-up cohorts and a frozen model. Yield-benefit claims need a comparison design that controls baseline differences and complete outcome denominators. Logging an intervention and a later harvest is insufficient to infer benefit.</p>
<h2>4. Remaining external requirements</h2><table><tr><th>Requirement</th><th>Current boundary</th></tr>{blockers}</table><p>Physical-phone and real-shed testing were explicitly excluded from this implementation request. Browser emulation is reported as browser emulation. Telugu copy is implemented; independent linguistic and departmental review is still required.</p>
<h2 class="page">5. Curated source inventory</h2><p>This inventory records inspected evidence and access limitations. It is a targeted review, not an exhaustive literature survey. Historical source-reported claims are not adopted as application performance.</p>{source_cards}
</body></html>'''
(ROOT/'artifacts/silksense-evidence-report.html').write_text(doc)
print('Wrote artifacts/silksense-evidence-report.html')
